// System Report: what a Wii U program sees when it asks the OS about itself, plus a
// live frame-time graph and the credits.

#include "app.h"
#include "audio.h"
#include "gfx.h"
#include "ui.h"

#include <coreinit/core.h>
#include <coreinit/memory.h>
#include <coreinit/systeminfo.h>
#include <coreinit/time.h>
#include <whb/gfx.h>

#include <math.h>
#include <stdio.h>
#include <string.h>

#define HIST 120

static float sHist[HIST];
static int sHistN;
static float sMin, sMax, sAvg;
static float sUiM[16];
static Batch *sTv, *sDrc;
static float sScroll;

static const char *kCredits[] = {
   "MUFFINEMU SHOWCASE",
   "THE WII U, IN YOUR HANDS.",
   "",
   "EVERYTHING YOU SAW AND HEARD",
   "WAS GENERATED BY CODE AT STARTUP.",
   "NO IMAGES, MODELS OR AUDIO FILES.",
   "NO NINTENDO ASSETS.",
   "",
   "MUFFIN VALLEY: 32,768 TRIANGLES",
   "PARTICLE STORM: 3,600 SPRITES",
   "SHADER LAB: RAYMARCHING ON THE GPU",
   "MIRROR HALL: RENDER TO TEXTURE",
   "CORE FRACTAL: THREE CPU CORES",
   "INPUT LAB: PAD, TOUCH, GYRO, RUMBLE",
   "SOUND ROOM: FOUR AX VOICES",
   "",
   "CREATED BY VOID",
   "BUILT WITH DEVKITPPC AND WUT",
   "SHADERS COMPILED WITH CAFEGLSL",
   "",
   "THANK YOU FOR TRYING MUFFINEMU",
};
#define CREDIT_LINES ((int)(sizeof(kCredits) / sizeof(kCredits[0])))

static void sys_enter(void) { sHistN = 0; sScroll = 0.0f; }
static void sys_leave(void) {}

static void row(Batch *b, float x, float y, const char *label, const char *value)
{
   b_text_shadow(b, x, y, 2.2f, C(0.75f, 0.7f, 1.0f, 1), label);
   b_text_shadow(b, x + 250.0f, y, 2.2f, C(1.0f, 0.95f, 0.85f, 1), value);
}

static void sys_update(float dt)
{
   m4_ortho_ui(sUiM);

   // frame time history
   memmove(&sHist[1], &sHist[0], sizeof(float) * (HIST - 1));
   sHist[0] = dt * 1000.0f;
   if (sHistN < HIST) sHistN++;
   sMin = 1e9f; sMax = 0.0f; sAvg = 0.0f;
   for (int i = 0; i < sHistN; i++) {
      if (sHist[i] < sMin) sMin = sHist[i];
      if (sHist[i] > sMax) sMax = sHist[i];
      sAvg += sHist[i];
   }
   sAvg /= (float)(sHistN ? sHistN : 1);

   sScroll += dt * 38.0f;
   if (sScroll > (float)CREDIT_LINES * 42.0f + 380.0f) sScroll = 0.0f;

   sTv = gfx_batch();
   sDrc = gfx_batch();
   Batch *b = sTv;
   char v[80];

   ui_header(b, "SYSTEM REPORT", "WHAT THE GUEST PROGRAM SEES");
   float x = 50.0f, y = 100.0f;
   ui_panel(b, 30.0f, 86.0f, 660.0f, 560.0f, 0.55f);

   snprintf(v, sizeof(v), "%d", (int)OSGetCoreCount());
   row(b, x, y, "CPU CORES", v); y += 34.0f;
   OSSystemInfo *si = OSGetSystemInfo();
   snprintf(v, sizeof(v), "%u MHZ", (unsigned)(si->coreClockSpeed / 1000000u));
   row(b, x, y, "CORE CLOCK", v); y += 34.0f;
   snprintf(v, sizeof(v), "%u MHZ", (unsigned)(si->busClockSpeed / 1000000u));
   row(b, x, y, "BUS CLOCK", v); y += 34.0f;
   uint32_t addr = 0, size = 0;
   if (OSGetMemBound(OS_MEM1, &addr, &size)) snprintf(v, sizeof(v), "%u MB", (unsigned)(size >> 20));
   else snprintf(v, sizeof(v), "N/A");
   row(b, x, y, "MEM1", v); y += 34.0f;
   if (OSGetMemBound(OS_MEM2, &addr, &size)) snprintf(v, sizeof(v), "%u MB", (unsigned)(size >> 20));
   else snprintf(v, sizeof(v), "N/A");
   row(b, x, y, "MEM2", v); y += 34.0f;
   GX2ColorBuffer *tvc = WHBGfxGetTVColourBuffer(), *drc = WHBGfxGetDRCColourBuffer();
   snprintf(v, sizeof(v), "%ux%u", (unsigned)tvc->surface.width, (unsigned)tvc->surface.height);
   row(b, x, y, "TV OUTPUT", v); y += 34.0f;
   snprintf(v, sizeof(v), "%ux%u", (unsigned)drc->surface.width, (unsigned)drc->surface.height);
   row(b, x, y, "GAMEPAD", v); y += 34.0f;

   OSCalendarTime ct;
   OSTicksToCalendarTime(OSGetTime(), &ct);
   snprintf(v, sizeof(v), "%04d-%02d-%02d", (int)ct.tm_year, (int)ct.tm_mon + 1, (int)ct.tm_mday);
   row(b, x, y, "DATE", v); y += 34.0f;
   snprintf(v, sizeof(v), "%02d:%02d:%02d", (int)ct.tm_hour, (int)ct.tm_min, (int)ct.tm_sec);
   row(b, x, y, "CLOCK", v); y += 34.0f;
   int up = (int)g_time;
   snprintf(v, sizeof(v), "%d:%02d", up / 60, up % 60);
   row(b, x, y, "UPTIME", v); y += 34.0f;
   snprintf(v, sizeof(v), "%d HZ  %s", SONG_RATE, g_audio.axOk ? "AX 4+1 VOICES" : (g_audio.ready ? "NO AX OUTPUT" : "SYNTHESIZING"));
   row(b, x, y, "AUDIO", v); y += 34.0f;
   row(b, x, y, "SHADERS", "2 GROUPS, LATTE, BLOCKS"); y += 34.0f;
   snprintf(v, sizeof(v), "%u", (unsigned)g_gfxVerts);
   row(b, x, y, "VERTICES/FRAME", v); y += 34.0f;
   snprintf(v, sizeof(v), "%u", (unsigned)g_gfxDraws);
   row(b, x, y, "DRAW CALLS", v);

   // frame-time graph
   float gx = 730.0f, gy = 110.0f, gw = 500.0f, gh = 300.0f;
   ui_panel(b, gx - 20.0f, gy - 24.0f, gw + 40.0f, gh + 120.0f, 0.55f);
   b_text_shadow(b, gx, gy - 16.0f, 2.2f, C(1, 1, 1, 0.95f), "FRAME TIME");
   b_rect(b, gx, gy + 14.0f, gw, gh - 14.0f, C(0, 0, 0, 0.5f));
   float top = 50.0f;   // ms at the top of the graph
   float y60 = gy + 14.0f + (gh - 14.0f) * (1.0f - 16.67f / top);
   b_line(b, gx, y60, gx + gw, y60, 1.5f, C(0.4f, 1.0f, 0.5f, 0.6f));
   b_text(b, gx + gw - 60.0f, y60 - 18.0f, 1.6f, C(0.4f, 1.0f, 0.5f, 0.8f), "60 FPS");
   float bw = gw / (float)HIST;
   for (int i = 0; i < sHistN; i++) {
      float ms = sHist[i] > top ? top : sHist[i];
      float h = (gh - 14.0f) * ms / top;
      Col c = sHist[i] < 17.5f ? C(0.4f, 1.0f, 0.5f, 1) : (sHist[i] < 34.0f ? C(1.0f, 0.85f, 0.3f, 1) : C(1.0f, 0.4f, 0.35f, 1));
      b_rect(b, gx + gw - (float)(i + 1) * bw, gy + gh - h, bw - 1.0f, h, c);
   }
   snprintf(v, sizeof(v), "AVG %.1f MS   MIN %.1f   MAX %.1f", sAvg, sMin, sMax);
   b_text_shadow(b, gx, gy + gh + 20.0f, 2.0f, C(1, 1, 1, 0.95f), v);
   snprintf(v, sizeof(v), "%.0f FPS", g_fps);
   b_text_shadow(b, gx, gy + gh + 52.0f, 3.2f, g_fps > 50.0f ? C(0.5f, 1, 0.6f, 1) : C(1, 0.8f, 0.4f, 1), v);
   ui_footer(b, "L/R: SCENE   +: HIDE TEXT   -: MUTE   B: MENU");

   // GamePad: credits roll
   b = sDrc;
   ui_header(b, "CREDITS", "SCROLLING FOREVER");
   for (int i = 0; i < CREDIT_LINES; i++) {
      float cy = 700.0f + (float)i * 42.0f - sScroll;
      if (cy < 70.0f || cy > 650.0f) continue;
      float fade = 1.0f;
      if (cy < 130.0f) fade = (cy - 70.0f) / 60.0f;
      if (cy > 590.0f) fade = (650.0f - cy) / 60.0f;
      bool title = (i == 0);
      Col c = title ? hsv(0.08f + 0.05f * fsin((float)g_time * 2.0f), 0.55f, 1.0f, fade) : C(1.0f, 0.95f, 0.88f, fade);
      b_text_center(b, VW * 0.5f, cy, title ? 5.0f : 2.6f, c, kCredits[i]);
   }
}

static void sys_draw(Target tg)
{
   Batch *bg = gfx_batch();
   if (tg == TARGET_TV) {
      ui_sky(bg, C(0.03f, 0.03f, 0.10f, 1), C(0.07f, 0.05f, 0.18f, 1), C(0.12f, 0.07f, 0.22f, 1));
   } else {
      b_rect_grad(bg, 0, 0, VW, VH, C(0.10f, 0.04f, 0.20f, 1), C(0.02f, 0.01f, 0.06f, 1));
   }
   gfx_draw_batch(bg, sUiM, BLEND_OPAQUE, DEPTH_OFF, NULL);
   gfx_draw_batch(tg == TARGET_TV ? sTv : sDrc, sUiM, BLEND_ALPHA, DEPTH_OFF, NULL);
}

const Scene scene_system = {
   "SYSTEM REPORT", "WHAT THE GUEST SEES: CORES, CLOCKS, MEMORY", sys_enter, sys_leave, sys_update, NULL, sys_draw, 16.0f,
};
